package agenda.registro.vista;

import agenda.registro.cliente.Cliente;
import java.awt.Color;

public class InicioSesionForm extends javax.swing.JPanel {

    private final Cliente socketCliente;
    private final VistaPrincipal vistaPrincipal;

    public InicioSesionForm(VistaPrincipal vistaPrincipal, Cliente socketCliente) {
        initComponents();
        this.socketCliente = socketCliente;
        this.vistaPrincipal = vistaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cajaTextoNombre = new javax.swing.JTextField();
        botonAtras = new javax.swing.JButton();
        botonAtras1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(825, 436));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA");

        cajaTextoNombre.setForeground(new java.awt.Color(204, 204, 204));
        cajaTextoNombre.setText(" Ingrese su nombre");
        cajaTextoNombre.setToolTipText("");
        cajaTextoNombre.setBorder(null);
        cajaTextoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaTextoNombreFocusLost(evt);
            }
        });
        cajaTextoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaTextoNombreMousePressed(evt);
            }
        });
        cajaTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoNombreActionPerformed(evt);
            }
        });

        botonAtras.setBackground(new java.awt.Color(0, 204, 255));
        botonAtras.setFont(new java.awt.Font("Leelawadee UI", 3, 12)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("INICIAR");
        botonAtras.setToolTipText("");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonAtras1.setBackground(new java.awt.Color(0, 204, 255));
        botonAtras1.setFont(new java.awt.Font("Leelawadee UI", 3, 12)); // NOI18N
        botonAtras1.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras1.setText("SALIR");
        botonAtras1.setToolTipText("");
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAtras1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cajaTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTextoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaTextoNombreFocusLost
        String textoOriginal = " Ingrese su nombre de usuario";
        if (cajaTextoNombre.getText().isEmpty()) {
            cajaTextoNombre.setText(textoOriginal);
            cajaTextoNombre.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cajaTextoNombreFocusLost

    private void cajaTextoNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaTextoNombreMousePressed
        cajaTextoNombre.setText("");
        cajaTextoNombre.setForeground(Color.black);

    }//GEN-LAST:event_cajaTextoNombreMousePressed

    private void cajaTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoNombreActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        String nombre = cajaTextoNombre.getText();
        cajaTextoNombre.setText("ingrese su nombre de usuario");
        cajaTextoNombre.setForeground(Color.gray);
        
        socketCliente.iniciarSesion(nombre);
        vistaPrincipal.cargarInicio(nombre);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonAtras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonAtras1;
    private javax.swing.JTextField cajaTextoNombre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
